#! /bin/sh

#export ENV=$HOME/.kshrc
#. $HOME/.profile

#xinput set-prop 7 297 0.5 &

pgrep -x sxhkd > /dev/null || sxhkd -c /home/sp/.config/sxhkd/sxhkdrc &
#pgrep -x bspwmbar > /dev/null || bspwmbar &
pgrep -x tint2 > /dev/null || tint2 &
pgrep -x emacs > /dev/null || emacs --fg-daemon &

nitrogen --restore &

#~/.xinitrc

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc monitor -d Slack Firefox Terminal Emacs Mail General

bspc config border_width 2
bspc config window_gap 15
bspc config focused_border_color #FF0000
#bspc config click_to_focus none

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Slack desktop='^1'
bspc rule -a Firefox desktop='^2'
bspc rule -a Mailspring desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled desktop='^4'
bspc rule -a Spotify state=tiled desktop='^9'
bspc rule -a Signal state=tiled desktop='^8'
bspc rule -a Discord state=tiled desktop='^8'
